# -*- coding: utf-8 -*-
"""
src/runtime/growth/__init__.py

Phase C.8.0 / C.8.2 Growth Proposal Runtime Integration —— 模块入口

只负责:
  - Event → Evaluation → Proposal(生成阶段)
  - Proposal 状态机管理(生命周期)
  - 记录 audit(runtime_growth_proposal_created / runtime_growth_proposal_transition)

绝不负责:
  - Proposal → Personality → SelfModel(应用阶段)
  - 自动 accept / apply
  - 任何人格变化
  - 任何 SelfModel 变化
"""
from __future__ import annotations

from .growth_proposal_runtime import (
    GROWTH_PROPOSAL_RUNTIME_SCHEMA_VERSION,
    GROWTH_PROPOSAL_RUNTIME_NAME,
    GROWTH_PROPOSAL_RUNTIME_VERSION,
    DEFAULT_CONFIDENCE_THRESHOLD,
    AUDIT_ACTION_PROPOSAL_CREATED,
    GrowthProposalRuntime,
    create_growth_proposal_runtime,
    safe_process_growth_signal,
)
from .growth_proposal_lifecycle import (
    GROWTH_PROPOSAL_LIFECYCLE_SCHEMA_VERSION,
    GROWTH_PROPOSAL_LIFECYCLE_NAME,
    GROWTH_PROPOSAL_LIFECYCLE_VERSION,
    STATE_PENDING,
    STATE_REVIEWING,
    STATE_APPROVED,
    STATE_REJECTED,
    STATE_NEEDS_REVIEW,
    STATE_READY_FOR_APPLY,
    ALL_STATES,
    TRANSITIONS,
    TERMINAL_STATES,
    INITIAL_STATE,
    AUDIT_ACTION_TRANSITION,
    REASON_ALREADY_IN_STATE,
    REASON_INVALID_TRANSITION,
    REASON_PROPOSAL_NOT_FOUND,
    is_valid_state,
    is_terminal_state,
    validate_transition,
    get_allowed_transitions,
    GrowthProposalLifecycleManager,
    create_growth_proposal_lifecycle,
    safe_transition,
)
from .growth_proposal_approval import (
    GROWTH_PROPOSAL_APPROVAL_SCHEMA_VERSION,
    GROWTH_PROPOSAL_APPROVAL_NAME,
    GROWTH_PROPOSAL_APPROVAL_VERSION,
    AUDIT_ACTION_APPROVED,
    AUDIT_ACTION_REJECTED,
    AUDIT_ACTION_REVOKED,
    ACTOR_HUMAN,
    ACTOR_ADMIN,
    ACTOR_SYSTEM,
    ALLOWED_ACTORS,
    REVOKE_REQUIRED_ACTORS,
    DEFAULT_ACTOR,
    REASON_UNAUTHORIZED,
    REASON_INVALID_STATE,
    REASON_PROPOSAL_NOT_FOUND as APPROVAL_REASON_PROPOSAL_NOT_FOUND,
    REASON_ALREADY_APPROVED,
    REASON_ALREADY_REJECTED,
    REASON_ALREADY_REVOKED,
    REASON_NOT_APPROVED,
    REASON_NOT_REVIEWING,
    REASON_NOT_READY_FOR_REVOKE,
    is_authorized,
    is_revoke_authorized,
    GrowthProposalApprovalWorkflow,
    create_growth_proposal_approval,
    safe_approve,
    safe_reject,
    safe_revoke,
)
from .growth_proposal_history import (
    GROWTH_PROPOSAL_HISTORY_SCHEMA_VERSION,
    GROWTH_PROPOSAL_HISTORY_NAME,
    GROWTH_PROPOSAL_HISTORY_VERSION,
    ACTION_CREATED,
    ACTION_REVIEWED,
    ACTION_APPROVED,
    ACTION_REJECTED,
    ACTION_REVOKED,
    ACTION_TRANSITION,
    ALL_ACTIONS as HISTORY_ALL_ACTIONS,
    AUDIT_ACTION_HISTORY_UPDATED,
    ACTOR_RUNTIME,
    INITIAL_VERSION,
    REASON_PROPOSAL_NOT_FOUND as HISTORY_REASON_PROPOSAL_NOT_FOUND,
    REASON_VERSION_NOT_FOUND,
    REASON_INVALID_VERSION,
    GrowthProposalHistory,
    create_growth_proposal_history,
    safe_record_event,
)

__all__ = [
    # C.8.0 Runtime
    "GROWTH_PROPOSAL_RUNTIME_SCHEMA_VERSION",
    "GROWTH_PROPOSAL_RUNTIME_NAME",
    "GROWTH_PROPOSAL_RUNTIME_VERSION",
    "DEFAULT_CONFIDENCE_THRESHOLD",
    "AUDIT_ACTION_PROPOSAL_CREATED",
    "GrowthProposalRuntime",
    "create_growth_proposal_runtime",
    "safe_process_growth_signal",
    # C.8.2 Lifecycle
    "GROWTH_PROPOSAL_LIFECYCLE_SCHEMA_VERSION",
    "GROWTH_PROPOSAL_LIFECYCLE_NAME",
    "GROWTH_PROPOSAL_LIFECYCLE_VERSION",
    "STATE_PENDING",
    "STATE_REVIEWING",
    "STATE_APPROVED",
    "STATE_REJECTED",
    "STATE_NEEDS_REVIEW",
    "STATE_READY_FOR_APPLY",
    "ALL_STATES",
    "TRANSITIONS",
    "TERMINAL_STATES",
    "INITIAL_STATE",
    "AUDIT_ACTION_TRANSITION",
    "REASON_ALREADY_IN_STATE",
    "REASON_INVALID_TRANSITION",
    "REASON_PROPOSAL_NOT_FOUND",
    "is_valid_state",
    "is_terminal_state",
    "validate_transition",
    "get_allowed_transitions",
    "GrowthProposalLifecycleManager",
    "create_growth_proposal_lifecycle",
    "safe_transition",
    # C.8.3 Approval Workflow
    "GROWTH_PROPOSAL_APPROVAL_SCHEMA_VERSION",
    "GROWTH_PROPOSAL_APPROVAL_NAME",
    "GROWTH_PROPOSAL_APPROVAL_VERSION",
    "AUDIT_ACTION_APPROVED",
    "AUDIT_ACTION_REJECTED",
    "AUDIT_ACTION_REVOKED",
    "ACTOR_HUMAN",
    "ACTOR_ADMIN",
    "ACTOR_SYSTEM",
    "ALLOWED_ACTORS",
    "REVOKE_REQUIRED_ACTORS",
    "DEFAULT_ACTOR",
    "REASON_UNAUTHORIZED",
    "REASON_INVALID_STATE",
    "APPROVAL_REASON_PROPOSAL_NOT_FOUND",
    "REASON_ALREADY_APPROVED",
    "REASON_ALREADY_REJECTED",
    "REASON_ALREADY_REVOKED",
    "REASON_NOT_APPROVED",
    "REASON_NOT_REVIEWING",
    "REASON_NOT_READY_FOR_REVOKE",
    "is_authorized",
    "is_revoke_authorized",
    "GrowthProposalApprovalWorkflow",
    "create_growth_proposal_approval",
    "safe_approve",
    "safe_reject",
    "safe_revoke",
    # C.8.4 History
    "GROWTH_PROPOSAL_HISTORY_SCHEMA_VERSION",
    "GROWTH_PROPOSAL_HISTORY_NAME",
    "GROWTH_PROPOSAL_HISTORY_VERSION",
    "ACTION_CREATED",
    "ACTION_REVIEWED",
    "ACTION_APPROVED",
    "ACTION_REJECTED",
    "ACTION_REVOKED",
    "ACTION_TRANSITION",
    "HISTORY_ALL_ACTIONS",
    "AUDIT_ACTION_HISTORY_UPDATED",
    "ACTOR_RUNTIME",
    "INITIAL_VERSION",
    "HISTORY_REASON_PROPOSAL_NOT_FOUND",
    "REASON_VERSION_NOT_FOUND",
    "REASON_INVALID_VERSION",
    "GrowthProposalHistory",
    "create_growth_proposal_history",
    "safe_record_event",
]
